apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.applicationName }}
  labels:
    app: {{ .Values.service.applicationName }}
spec:
  type: {{ .Values.service.typePort}}
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.applicationName }}
  selector:
    app: {{ .Values.service.applicationName }}


