image:
  repository: docker.io/vinho0onguyen/my-api
  tag: 623687282
  pullPolicy: Always
  pullSecret: harbor-registry

service:
  applicationName: notice-service
  replicas: 2
  port: 5000
  typePort: NodePort


limit:
  cpu: 500m
  memory: 512Mi
request:
  cpu: 200m
  memory: 512Mi



strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 25%

